development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  database: demo_api_development
  username: chris
  password: chris

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  database: demo_api_development
  username: chris
  password: chris
