# STRIPE_PUBLISHABLE_KEY: "pk_test_51JSn1ZSIE4jcZ9Lx1S0xue8jN7utTceEq9afFAIqDyuLOrKwGiCADw4LqXdz7jai2uTM7dfdBUm8nIMj5s9Kek3Z00WAnlzh8P"

# STRIPE_SECRET_KEY: "sk_test_51JSn1ZSIE4jcZ9LxX804qm4HlMGAgW59OUvICBBTwZZdPvqFVLhq3LmYOSWcs55sTu1prYKZR504U02x0l0wmJ1900jAyTGKF3"
# SHOPIFY_HOSTNAME : "rishabhaggarwal"
# SHOPIFY_ACCESS_TOKEN : "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"
# SHOPIFY_HOSTNAME_UK : "rishabhaggarwal-2"
# SHOPIFY_ACCESS_TOKEN_UK : "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"

DEMO_API_DATABASE_USERNAME: chris
DEMO_API_DATABASE_PASSWORD: chris
DEVISE_JWT_SECRET_KEY: b18549d415b5e50c76b55b590780bef4f9511a39dd14cb7c29fbd6dc23aadd3160da06b5a89c09ea6b171cd4c36567a69206b228c8e2becbdfd7f7788fc6e7c4